export const permissionSeeds = [
  //organization permissions
  { name: 'create-contract', module: 'organization', operationDB: 'create' },
  { name: 'invite-to-organization', module: 'organization', operationDB: 'create' },
  { name: 'create-infrastructure', module: 'organization', operationDB: 'create' },
  { name: 'view-organization-infras', module: 'organization', operationDB: 'create' },
  { name: 'view-organization', module: 'organization', operationDB: 'create' },
  { name: 'update-organization', module: 'organization', operationDB: 'create' },
  { name: 'delete-organization', module: 'organization', operationDB: 'create' },
  { name: 'view-organization-members', module: 'organization', operationDB: 'create' },
  { name: 'view-organization-settings', module: 'organization', operationDB: 'create' },
  { name: 'create-resource', module: 'organization', operationDB: 'create' },
  { name: 'view-organization-resources', module: 'organization', operationDB: 'create' },
  // resource permissions
  { name: 'update-resource', module: 'organization', operationDB: 'create' },
  { name: 'update-resource-settings', module: 'organization', operationDB: 'create' },
  { name: 'view-resource-settings', module: 'organization', operationDB: 'create' },
  { name: 'create-resource-reservation-rate', module: 'organization', operationDB: 'create' },
  { name: 'update-resource-reservation', module: 'organization', operationDB: 'create' },
  { name: 'update-resource-reservation', module: 'organization', operationDB: 'create' },
  { name: 'update-resource-properties', module: 'organization', operationDB: 'create' },
  { name: 'view-resource-settings', module: 'organization', operationDB: 'create' },
  { name: 'view-resource-managers', module: 'organization', operationDB: 'create' },
  { name: 'create-resource-reservation', module: 'organization', operationDB: 'create' },
  { name: 'delete-resource-manager', module: 'organization', operationDB: 'create' },
  { name: 'update-resource-managers', module: 'organization', operationDB: 'create' },
  { name: 'view-resource-EventsByRange', module: 'organization', operationDB: 'create' },
  { name: 'view-all-resource-reservations', module: 'organization', operationDB: 'create' },
];
