version: '3'

services:
  api:
    build:
      context: ../../
      dockerfile: devops/staging/api.dockerfile
    environment:
      PORT: 3000
      ENV: staging
      TOKEN_SECRET: jwt_secret_2121
    ports:
      - '80:3000'
