version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    container_name: postgres_container
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: localapi
      POSTGRES_PASSWORD: 'localapi'
    ports:
      - '5432:5432'
